# Generated by Django 6.0.5 on 2026-06-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=15)),
                ('token_number', models.PositiveIntegerField()),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending/Waiting'), ('CALLED', 'Called/Active'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'NO Show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='clinics.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'booking_date', 'token_number'), name='unique_doctor_date_token')],
            },
        ),
    ]
